export default [
  {
    id: crypto.randomUUID(),
    date: '1 Nisan',
    rating: 77,
    emotions: [
      { icon: '😊', text: 'Memnun' },
      { icon: '☺️', text: 'Rahat' },
      { icon: '🙏', text: 'Minnettar' },
      { icon: '️️️⚡️', text: 'Enerjik' },
    ],
    activities: [
      { icon: '🏃‍♂️', text: 'Çalışıyor' },
      { icon: '️️️🧘‍♂️', text: 'Meditasyon' },
      { icon: '️✍️', text: 'Dergi' },
      { icon: '️📖', text: 'Kitap Okuma' },
      { icon: '️️👪', text: 'Aile Zamanı' },
    ],
    note: `Çok heyecan verici bir şey olmadı ama bugün oldukça güzel bir gündü. "Kendime ayırdığım zaman" ile aileme ayırdığım zaman arasında iyi bir denge kurdum ve günün sonunda kendimi çok rahatlamış ve memnun hissettim.`,
  },
  {
    id: crypto.randomUUID(),
    date: '2 Nisan',
    rating: 96,
    emotions: [
      { icon: '😇', text: 'Gururlu' },
      { icon: '🥰', text: 'Takdir Edildi' },
      { icon: '😃', text: 'Neşeli' },
      { icon: '️🥳', text: 'Kutlayıcı' },
    ],
    activities: [
      { icon: '🏆', text: 'Kişisel Zaferi' },
      { icon: '️️️💪', text: 'Kişisel Gelişim' },
      { icon: '️🍛', text: 'Güzel Yemek' },
      { icon: '️🛌', text: 'İyi Uyku' },
      { icon: '️️👪', text: 'Aile Zamanı' },
    ],
    note: 'Son üç aydır üzerinde çalıştığım büyük projemi nihayet bitirdim ve ekibimin bir üyesi olarak kendimi geliştirdiğimi hissediyorum. İş arkadaşlarımın hepsi iyi bir iş çıkardığımı söyledi. Ailemle birlikte kutlamak için akşam yemeğe çıktık.',
  },
  {
    id: crypto.randomUUID(),
    date: '3 Nisan',
    rating: 44,
    emotions: [
      { icon: '😃', text: 'Heyecanlı' },
      { icon: '🤞', text: 'Umutlu' },
      { icon: '😞', text: 'Hayal kırıklığına uğradım' },
      { icon: '️😱', text: 'Şok oldum' },
      { icon: '😵', text: 'Kafası karışık' },
      { icon: '🎢', text: 'Duygusal Roller Coaster' },
    ],
    activities: [
      { icon: '⬅️', text: 'Kişisel Aksaklık' },
      { icon: '️️️‍👨‍💻', text: 'İş Sorunları' },
      { icon: '️🍽', text: 'Kaçırılan Yemek' },
      { icon: '️🥱', text: 'Kötü Uyku' },
    ],
    note: `Dünkü başarımdan sonra, bugün nihayet beklediğim büyük terfiyi alacağımı umarak işe gittim ama bunun yerine patronum bana hala "gelişmem gereken yerler" olduğunu ve bu yıl yaptığım pek çok işten memnun olmadığını söyledi. Beni terfi ettirmektense kovmaya daha yakın olduğunu hissettim`,
  },
  {
    id: crypto.randomUUID(),
    date: '4 Nisan',
    rating: 28,
    emotions: [
      { icon: '😤', text: 'Küskün' },
      { icon: '😡', text: 'Kızgın' },
      { icon: '😬', text: 'Endişeli' },
      { icon: '☹️', text: 'Üzgün' },
      { icon: '🌪', text: 'Çalkantılı' },
      { icon: '️😴', text: 'Yorgun' },
    ],
    activities: [
      { icon: '🛋', text: 'Oturup Duruyor' },
      { icon: '️️️‍📺', text: 'Televizyon İzliyor' },
      { icon: '️🎮', text: 'Oyun' },
      { icon: '️🍺', text: 'İçiyor' },
    ],
    note: `Bugün üretken hiçbir şey yapmadım ve kendime dikkat etmedim. Sadece "kendimi bıraktım" ve dikkatimi dağıtmaya çalıştım. Dün işte olanları düşündükçe kendimi daha da kötü hissediyorum.`,
  },
  {
    id: crypto.randomUUID(),
    date: '5 Nisan',
    rating: 12,
    emotions: [
      { icon: '😥', text: 'Ağlamaklı' },
      { icon: '😫', text: 'Üzgün' },
      { icon: '😬', text: 'Endişeli' },
      { icon: '😧', text: 'Korkmuş' },
    ],
    activities: [
      { icon: '🍩', text: 'Abur Cubur Yemek' },
      { icon: '️️️‍📱', text: 'Anlamsız Kaydırma' },
      { icon: '️🚬', text: 'Sigara İçme' },
      { icon: '️🍺', text: 'İçiyor' },
    ],
    note: `Bugün daha da kötü hissetim ve kendimi daha da "bıraktım". Hatta aylardır ilk kez sigara içtim. Aşağı doğru bir sarmal içindeyim. Yarın kendimi bundan kurtarmam gerekiyor.`,
  },
  {
    id: crypto.randomUUID(),
    date: '6 Nisan',
    rating: 42,
    emotions: [
      { icon: '😐', text: 'Ciddi' },
      { icon: '🧐', text: 'Kendini Eleştiren' },
      { icon: '🙄', text: 'Utangaç' },
      { icon: '🙌', text: 'Kararlı' },
    ],
    activities: [
      { icon: '🏃‍♂️', text: 'Koşu' },
      { icon: '️️️🧘‍♂️', text: 'Meditasyon' },
      { icon: '️️️🏋️‍♀️', text: 'Ağırlık Kaldırma' },
      { icon: '️️️🥗', text: 'Sağlıklı Beslenme' },
      { icon: '️️️💭', text: 'Kendi İçine Dönme' },
    ],
    note: `Bugün kendimi son birkaç gündür nasıl davrandığım konusunda utandım. Bugün işleri değiştirmeye karar verdiğim gün olacaktı. Kendi içime dönüş yaptım, kendime bakım yaptım ve günün sonunda biraz daha iyi hissettim. Yarın aynı şekilde devam etmeye çalışacağım.`,
  },
  {
    id: crypto.randomUUID(),
    date: '7 Nisan',
    rating: 64,
    emotions: [
      { icon: '💪', text: 'Güçlü' },
      { icon: '🤨', text: 'Belirsiz' },
      { icon: '🤔', text: 'Düşünceli' },
    ],
    activities: [
      { icon: '🚴‍♀️', text: 'Bisiklet Sürme' },
      { icon: '️️️🚶', text: 'Yürüyüş' },
      { icon: '️️️🥗', text: 'Sağlıklı Beslenme' },
      { icon: '️️️💭', text: 'Kendi İçine Dönme' },
    ],
    note: `Bugün biraz daha düşündüm ve fark ettim ki: Patronum aslında işimden memnun değil gibi görünmüyor. Sadece beni sevmiyor gibi. Peki, eğer bu doğruysa ne yapmalıyım? Çıkmaza girmiş bir işte miyim?`,
  },
  {
    id: crypto.randomUUID(),
    date: '8 Nisan',
    rating: 84,
    emotions: [
      { icon: '😌', text: 'Sakin' },
      { icon: '🙌', text: 'Kararlı' },
      { icon: '😎', text: 'Kararlı' },
    ],
    activities: [
      { icon: '🥾', text: 'Doğa Yürüyüşü' },
      { icon: '️️️💭', text: 'Kendi İçine Dönme' },
      { icon: '️️️❗️', text: 'Büyük Karar' },
    ],
    note: `Bugün doğaya doğru bir yürüyüşe çıktım. Orada biraz daha düşündüm ve büyük bir karara vardım: Evet, çıkmaza girmiş bir işteyim ve uzun süredir bundan keyif almadım, bu yüzden istifa etmeliyim. Yarın istifamı vereceğim.`,
  },
  {
    id: crypto.randomUUID(),
    date: '9 Nisan',
    rating: 65,
    emotions: [
      { icon: '😮', text: 'Rahatlamış' },
      { icon: '😬', text: 'Endişeli' },
      { icon: '😊', text: 'Mutlu' },
      { icon: '😢', text: 'Üzgün' },
      { icon: '😡', text: 'Sinirli' },
      { icon: '🎢', text: 'Duygusal Roller Coaster' },
    ],
    activities: [
      { icon: '🚨', text: 'Büyük Olay' },
      { icon: '️️️🔚', text: 'Bir Dönemin Sonu' },
      { icon: '️️️🆕', text: 'Yeni Başlangıç' },
      { icon: '️️️🥊', text: 'Boks' },
      { icon: '️️️🏋️‍♀️', text: 'Ağırlık Kaldırma' },
    ],
    note: `Başardım. İstifa ettim. İstifamı verdim ve patronum sadece gidip toplamamı ve hemen ayrılmamı söyledi. İki hafta boyunca etrafta olmamı istemiyordu. Dürüst olmak gerekirse, konuda oldukça kaba biriydi. Kararımı verdiğim için mutluyum ve hoşlanmadığım bir işe geri dönmek zorunda olmadığımı bilmek rahatlatıcı. Ancak bazı meslektaşlarımı özleyeceğim ve bir sonraki adımda ne yapacağıma dair biraz endişeli hissediyorum. Muhtemelen bu işi bırakmadan önce yeni bir iş bulmalıydım. Buharını atmak için biraz boks ve ağırlık kaldırma yaptım.`,
  },
  {
    id: crypto.randomUUID(),
    date: '10 Nisan',
    rating: 41,
    emotions: [
      { icon: '🤯', text: 'Beyin Patlamış' },
      { icon: '😲', text: 'Şaşkın' },
      { icon: '😭', text: 'Üzgün' },
    ],
    activities: [
      { icon: '💻', text: 'İş Arama' },
      { icon: '️️️📞', text: 'Aramalar Yapma' },
      { icon: '️️️👎', text: 'Reddedilme Deneyimi' },
    ],
    note: `Endüstrimde tanıdığım insanlara telefon ettim ve ana iş sitelerinde bulunan tüm açık pozisyonlara baktım. Birkaçına başvurdum ancak çok az pozisyon mevcut. İş piyasasının ne kadar kötü olduğuna şaşırıyorum. Bir işe alım yöneticisi bana yeni doldurdukları düşük ücretli bir pozisyon için 150 başvuru aldığını söyledi. Zaten birkaç geri dönüş aldım ve hepsi olumsuzdu.`,
  },
  {
    id: crypto.randomUUID(),
    date: '11 Nisan',
    rating: 22,
    emotions: [
      { icon: '😬', text: 'Endişeli' },
      { icon: '😭', text: 'Üzgün' },
      { icon: '😧', text: 'Korkmuş' },
      { icon: '😫', text: 'Pişman' },
    ],
    activities: [
      { icon: '💻', text: 'İş Arama' },
      { icon: '️️️👎', text: 'Reddedilme Deneyimi' },
      { icon: '️🍺', text: 'İçki İçme' },
      { icon: '️🚬', text: 'Sigara İçme' },
    ],
    note: `Daha fazla reddedilme. İş arama konusunda hiç şansım yok. Şimdi korkuyorum, eğer yeni bir iş bulamazsam ne olacak? Eski işimi bu kadar aceleyle bırakmamalıydım gerçekten. Daha fazla düşünmeliydim ve bu kadar düşüncesiz olmamalıydım. Büyük bir hata yaptığımı düşünüyorum.`,
  },
  {
    id: crypto.randomUUID(),
    date: '12 Nisan',
    rating: 17,
    emotions: [
      { icon: '😭', text: 'Umutsuz' },
      { icon: '😱', text: 'Dehşete Düşmüş' },
    ],
    activities: [
      { icon: '🛏', text: 'Yatakta Yatma' },
      { icon: '️️️💦', text: 'Ağlama' },
    ],
    note: `Bugün tamamen çöktüm. Tüm gün yatakta kaldım ve ağladım. Yeni bir iş bulamayacağımı düşünüyorum ve nasıl geçineceğimi bilmiyorum.`,
  },
  {
    id: crypto.randomUUID(),
    date: '13 Nisan',
    rating: 6,
    emotions: [
      { icon: '😶', text: 'Hissetmiyorum' },
      { icon: '🏳', text: 'Pes Ettim' },
    ],
    activities: [
      { icon: '🍨', text: 'Dondurma Yeme' },
      { icon: '🍰', text: 'Kek Yeme' },
    ],
    note: `Dünkü gibi, şimdi bir şekilde daha da kötü hissediyorum. Temelde yaptığım şey dondurma ve kek yiyerek gün boyunca oturan, işsiz ve geliri olmayan biri olmuşum gibi.`,
  },
  {
    id: crypto.randomUUID(),
    date: '14 Nisan',
    rating: 100,
    emotions: [
      { icon: '☺️', text: 'Sevinç' },
      { icon: '😅', text: 'Rahatlamış' },
      { icon: '🥳', text: 'Kutlama' },
      { icon: '🤩', text: 'Hayran Kalmış' },
    ],
    activities: [
      { icon: '🎁', text: 'Beklenmeyen Hediye Aldım' },
      { icon: '️️️🍀', text: 'Şanslıydım' },
      { icon: '️️️🎉', text: 'Yeni Başlangıç' },
      { icon: '️️️👽', text: 'Paranormal Aktivite' },
    ],
    note: `Bugün tamamen beklenmedik bir şey oldu. Bu sabah hala korkunç hissediyordum ve birkaç saat yatakta yattıktan sonra biraz daha kek almak için kalkmaya karar verdim. Ancak mutfağa girdiğimde, inanılmaz bir şey gördüm: buzdolabımın önünde üç uzaylı duruyordu. "Barış içinde geldikama başka bir dilim kek yiyemezsin.Seni daha iyi bir dünyaya götürmek için buradayız." dediler ve gemilerine ışınlandım. Dünya'dan ayrıldık, bir solucan deliğine girdik ve birkaç dakika içinde galaksinin diğer tarafındaydık. Daha sonra onların gezegenine indik, Gorzarg 7 burada beni başka bir sürpriz bekliyordu:yüksek derecede gelişmiş bir toplum, evrensel temel gelir uygulamış ve çoğu iş AI destekli robotlar tarafından otomatik hale getirilmiş. Artık bir işle ilgilenmeme gerek yok.Haftayı bitirmenin harika bir yolu var`,
  },
]
